// UX-11A.5c.4 — test-only fixtures (excluded from the app build): genuine KEEP
// final prescriptions produced by the engine (finalPrescriptionV2.json,
// regenerated by web/scripts/generate-final-prescription-v2-fixtures.mjs).
import fixtures from "./finalPrescriptionV2.json";

export type FixtureKind = "STRENGTH_LOWER" | "STRENGTH_UPPER" | "DH_TECHNICAL" | "AEROBIC_BASE";

/** The live daily-run shape, the persisted row shape and the decoder input of one KEEP final prescription (deep copies). */
export function keepFinalPrescription(kind: FixtureKind) {
  const fp = JSON.parse(JSON.stringify((fixtures.finalPrescriptions as Record<string, unknown>)[kind])) as {
    id: string;
    decisionId: string;
    schemaVersion: string;
    catalogVersion: string;
    structure: Record<string, any>;
  };
  return {
    live: fp,
    row: { id: fp.id, decision_id: fp.decisionId, schema_version: fp.schemaVersion, catalog_version: fp.catalogVersion, structure: fp.structure },
    record: { id: fp.id, decisionId: fp.decisionId, schemaVersion: fp.schemaVersion, catalogVersion: fp.catalogVersion, structure: fp.structure },
  };
}

export const FIXTURES_GENERATED_FROM = fixtures.generatedFrom;
