import { describe, expect, it } from "vitest";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { fakeBackend, prescriptionView } from "../../test/guidedSessionFakeBackend";
import { GuidedSessionHarness as Harness } from "../../test/GuidedSessionHarness";
import { keepFinalPrescription } from "../../test/fixtures/finalPrescriptionV2Fixtures";
import { decodeFinalPrescriptionV2 } from "../finalPrescriptionV2/decodeFinalPrescriptionV2";
import { resolveSessionModule } from "./sessionModules";
import { RECOVERY_COPY } from "./recovery/RecoverySessionModule";
import type { DrillItemView, ExerciseItemView, FinalPrescriptionV2View } from "../finalPrescriptionV2/finalPrescriptionV2Types";

// A04 — MODIFY / REPLACE final prescriptions made by the engine
// (fixtures regenerated by scripts/generate-final-prescription-v2-fixtures.mjs)
// decode, open in the guided session and complete, through the real shell,
// hook and modules against the backend double (record_session_execution rules,
// F-6C included).

const phase = () => screen.getByRole("status").getAttribute("data-phase");
const completeButton = () => screen.getByRole("button", { name: "Terminer la séance" });
const work = (p: FinalPrescriptionV2View) => p.blocks.filter((b) => b.role === "main" || b.role === "complementary").flatMap((b) => b.items as ExerciseItemView[]);

async function startSession() {
  await userEvent.click(await screen.findByRole("button", { name: "Commencer la séance" }));
  await waitFor(() => expect(phase()).toBe("active"));
}

async function recordFirstSet(it: ExerciseItemView) {
  await userEvent.click(screen.getByRole("button", { name: `Saisir la série 1 — ${it.name}` }));
  const label = it.measure.type === "duration" ? /Secondes réalisées/ : /Répétitions réalisées/;
  await userEvent.type(screen.getByLabelText(label), it.measure.type === "duration" ? "30" : "8");
  await userEvent.click(screen.getByRole("button", { name: "Enregistrer la série" }));
  await waitFor(() => expect(within(document.querySelector(`[data-slot="${it.prescriptionItemId}#1"]`) as HTMLElement).getByTestId("slot-result").textContent).toMatch(/^Réalisé/));
}

describe("A04 — adapted prescriptions decode with their real content", () => {
  it.each(["MODIFY_STRENGTH_LOWER", "MODIFY_DH_TECHNICAL", "REPLACE_DH_TO_STRENGTH", "REPLACE_TO_RECOVERY"] as const)("%s decodes (no partial rendering) and resolves its guided module", (kind) => {
    const r = decodeFinalPrescriptionV2(keepFinalPrescription(kind).record);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(resolveSessionModule(r.view).kind).toBe({ MODIFY_STRENGTH_LOWER: "strength", MODIFY_DH_TECHNICAL: "dh_technical", REPLACE_DH_TO_STRENGTH: "strength", REPLACE_TO_RECOVERY: "recovery" }[kind]);
  });

  it("MODIFY Force: LIGHT dose on the planned exercises (3 sets on the principal, RPE 5–6)", () => {
    const planned = prescriptionView("STRENGTH_LOWER");
    const modified = prescriptionView("MODIFY_STRENGTH_LOWER");
    expect(work(modified).map((i) => i.exerciseId)).toEqual(work(planned).map((i) => i.exerciseId));
    expect(work(modified)[0]).toMatchObject({ sets: 3, rpeTarget: { min: 5, max: 6 } });
    expect(work(planned)[0]).toMatchObject({ sets: 4 });
  });

  it("MODIFY DH: the same drill, 4 passages", () => {
    const drill = (p: FinalPrescriptionV2View) => p.blocks.find((b) => b.role === "main")!.items[0] as DrillItemView;
    expect(drill(prescriptionView("MODIFY_DH_TECHNICAL"))).toMatchObject({ drillId: drill(prescriptionView("DH_TECHNICAL")).drillId, passes: 4 });
  });
});

describe("A04 — the guided session opens and completes adapted prescriptions", () => {
  it("E — REPLACE DH → Force: real Force slots; completion needs a performed set (F-6C), then completes", async () => {
    const p = prescriptionView("REPLACE_DH_TO_STRENGTH");
    const b = fakeBackend({ prescription: p });
    render(<Harness deps={b.deps} />);
    await startSession();
    expect(screen.getByTestId("strength-progress")).toHaveTextContent(`0 / ${work(p).reduce((n, i) => n + i.sets, 0)}`);
    expect(completeButton()).toBeDisabled();
    await recordFirstSet(work(p)[0]!);
    await userEvent.click(completeButton());
    await userEvent.click(await screen.findByRole("button", { name: "Terminer quand même" }));
    await waitFor(() => expect(phase()).toBe("completed"));
  });

  it("D — MODIFY Force: the LIGHT slots open and complete", async () => {
    const p = prescriptionView("MODIFY_STRENGTH_LOWER");
    const b = fakeBackend({ prescription: p });
    render(<Harness deps={b.deps} />);
    await startSession();
    await recordFirstSet(work(p)[0]!);
    await userEvent.click(completeButton());
    await userEvent.click(await screen.findByRole("button", { name: "Terminer quand même" }));
    await waitFor(() => expect(phase()).toBe("completed"));
    const set = b.executions[0]!.exercise_set_results[0]!;
    expect(set.prescription_item_id).toBe(work(p)[0]!.prescriptionItemId); // the ADAPTED item id, never the planned one
  });

  it("C — MODIFY DH: 4 pass slots", async () => {
    const b = fakeBackend({ prescription: prescriptionView("MODIFY_DH_TECHNICAL") });
    render(<Harness deps={b.deps} />);
    await startSession();
    expect(screen.getByTestId("dh-progress")).toHaveTextContent("0 / 4 passages enregistrés");
  });

  it("REPLACE → active recovery: the content is shown, nothing to measure, the rider completes it", async () => {
    const b = fakeBackend({ prescription: prescriptionView("REPLACE_TO_RECOVERY") });
    render(<Harness deps={b.deps} />);
    await startSession();
    expect(screen.getByTestId("recovery-note")).toHaveTextContent(RECOVERY_COPY.note);
    expect(screen.queryByTestId("results-placeholder")).toBeNull();
    expect(completeButton()).toBeEnabled();
    await userEvent.click(completeButton());
    await waitFor(() => expect(phase()).toBe("completed"));
  });
});
