// UX-11C.1 — typed web client of the `session-execution` Edge Function
// (supabase/functions/session-execution, UX-11B.2 / 11B.2.5).
//
// Contract (never duplicated here, only typed): POST, authenticated user
// (athlete resolved server-side through RLS), one batch
// { execution?, events?, sets?, activities? } handed to record_session_execution
// in ONE transaction. Ids are generated by the device: replaying the same
// id with the same content is a no-op ("unchanged"), the same id with other
// content is `id_conflict`. A new execution must come with its `started`
// event and reference the day's CURRENT final prescription
// (`final_prescription_not_current` otherwise); later events reference the
// existing execution. 200 → { inserted, unchanged }; business rejections →
// 4xx { error: { code, message, target? } }.
import { FunctionsFetchError, FunctionsHttpError, FunctionsRelayError } from "@supabase/supabase-js";
import { supabase } from "../../lib/supabase";

export type ExecutionEventType = "started" | "paused" | "resumed" | "completed" | "abandoned";

export interface ExecutionCreateInput {
  id: string;
  session_date: string;
  started_at: string;
  final_prescription_id: string;
  comment: null;
}

export interface ExecutionEventInput {
  id: string;
  execution_id: string;
  event_type: ExecutionEventType;
  occurred_at: string;
}

/**
 * UX-11C.2 / 11C.3 — one performed set (Force) or pass (DH drill, the
 * ordinal travels in `set_number`) of a PRESCRIBED item (never an "other
 * exercise" here). `exercise_id` is copied by the server and never sent.
 * A correction is a new row with `supersedes_id` = the original (same item,
 * same ordinal); `done` is always true: an absent set / pass has no row.
 */
export type SetResultInput =
  | {
      id: string;
      execution_id: string;
      prescription_item_id: string;
      set_number: number;
      done: true;
      measure_type: "reps" | "duration";
      measure_value: number;
      load_kg: number | null;
      rpe_actual: number | null;
      supersedes_id: string | null;
      occurred_at: string;
    }
  | {
      id: string;
      execution_id: string;
      prescription_item_id: string;
      /** The pass ordinal (1..measure.count). */
      set_number: number;
      done: true;
      measure_type: "pass";
      /** A pass carries no value. */
      measure_value: null;
      /** Was the drill's success criterion met on this pass? null = not assessed. */
      success: boolean | null;
      supersedes_id: string | null;
      occurred_at: string;
    };

export type ForceSetInput = Extract<SetResultInput, { measure_type: "reps" | "duration" }>;
export type PassResultInput = Extract<SetResultInput, { measure_type: "pass" }>;

/** Executions, events and (UX-11C.2) set results; activities belong to the endurance module (later). */
export interface SessionExecutionBatch {
  execution?: ExecutionCreateInput;
  events: ExecutionEventInput[];
  sets?: SetResultInput[];
}

export interface SessionExecutionOutcome {
  inserted: Record<string, string[]>;
  unchanged: Record<string, string[]>;
}

export interface SessionExecutionError {
  /** Stable backend code (e.g. final_prescription_not_current, active_execution_exists), or network_error / unknown_error. */
  code: string;
  status: number | null;
  /** True when re-sending the SAME batch (same ids) is the right recovery. */
  retryable: boolean;
}

export type SessionExecutionResult = { ok: true; value: SessionExecutionOutcome } | { ok: false; error: SessionExecutionError };

async function mapError(error: unknown): Promise<SessionExecutionError> {
  if (error instanceof FunctionsHttpError) {
    const response = error.context as Response;
    let code = "unknown_http_error";
    try {
      const body = (await response.json()) as { error?: { code?: unknown } };
      if (typeof body?.error?.code === "string") code = body.error.code;
    } catch {
      /* non-JSON body: keep the generic code */
    }
    // 5xx: the same batch may be re-sent safely (idempotent ids).
    return { code, status: response.status, retryable: response.status >= 500 };
  }
  if (error instanceof FunctionsRelayError || error instanceof FunctionsFetchError) {
    return { code: "network_error", status: null, retryable: true };
  }
  return { code: "unknown_error", status: null, retryable: true };
}

export async function postSessionExecutionBatch(batch: SessionExecutionBatch): Promise<SessionExecutionResult> {
  const { data, error } = await supabase.functions.invoke<unknown>("session-execution", { body: batch });
  if (error) return { ok: false, error: await mapError(error) };
  const body = data as Partial<SessionExecutionOutcome> | null;
  if (!body || typeof body.inserted !== "object" || typeof body.unchanged !== "object") {
    return { ok: false, error: { code: "invalid_response", status: 200, retryable: true } };
  }
  return { ok: true, value: { inserted: body.inserted as Record<string, string[]>, unchanged: body.unchanged as Record<string, string[]> } };
}
