/**
 * V0.4_102 — real local Supabase proof for `abandon_training_plan_version`
 * and its wrapper: a real draft version, abandoned through the actual RPC
 * (never mocked) — idempotence, the draft-only guard, the mandatory-reason
 * guard, and cross-athlete rejection, all against the real schema. This is
 * the integration coverage `accept_training_plan_version` never got
 * (V0.4_102 audit finding) — deliberately not reproduced here.
 *
 * OPT-IN ONLY, hard-bound to loopback — see testDb.ts's createTestClient().
 */
import { afterEach, beforeAll, describe, expect, it } from "vitest";
import type { SupabaseClient } from "@supabase/supabase-js";
import {
  createTestClient,
  createTestAthlete,
  deleteTestAthlete,
  generateTrainingPlan,
  generateAndAcceptTrainingPlan,
  isLoopbackSupabaseUrl,
  resolveTestSupabaseUrl,
  type TestAthlete,
} from "./testDb.js";
import { abandonTrainingPlanVersionRpc, AbandonTrainingPlanVersionRpcError } from "../../src/supabase/abandonTrainingPlanVersionRpc.js";

const SERVER_KEY = process.env.SUPABASE_SECRET_KEY ?? process.env.SUPABASE_SERVICE_ROLE_KEY;
const RESOLVED_ADMIN_URL = resolveTestSupabaseUrl();
const INTEGRATION_ENABLED =
  process.env.RUN_LOCAL_SUPABASE_INTEGRATION === "1" && !!SERVER_KEY && isLoopbackSupabaseUrl(RESOLVED_ADMIN_URL);

describe.skipIf(!INTEGRATION_ENABLED)("V0.4_102 — abandon_training_plan_version (real local Supabase)", () => {
  let admin: SupabaseClient;
  let athleteA: TestAthlete;
  let athleteB: TestAthlete;

  beforeAll(() => {
    admin = createTestClient();
  });

  afterEach(async () => {
    if (athleteA) await deleteTestAthlete(admin, athleteA);
    if (athleteB) await deleteTestAthlete(admin, athleteB);
  });

  it("abandons a real draft version: fresh call succeeds with a new transition id", async () => {
    athleteA = await createTestAthlete(admin, "V0.4_102 abandon draft");
    const plan = await generateTrainingPlan(admin, athleteA.athleteId, {
      horizonStartDate: "2026-10-01",
      horizonEndDate: "2026-10-07",
      sessions: [{ date: "2026-10-01", kind: "REST" }],
    });

    const result = await abandonTrainingPlanVersionRpc(admin, athleteA.athleteId, plan.planVersionId, "regenerated by athlete");

    expect(result.idempotentReplay).toBe(false);
    expect(result.abandonedTransitionId).toBeDefined();
    expect(result.planVersionId).toBe(plan.planVersionId);
  });

  it("a second abandon call on the same version is an idempotent no-op, not an error", async () => {
    athleteA = await createTestAthlete(admin, "V0.4_102 double abandon");
    const plan = await generateTrainingPlan(admin, athleteA.athleteId, {
      horizonStartDate: "2026-10-01",
      horizonEndDate: "2026-10-07",
      sessions: [{ date: "2026-10-01", kind: "REST" }],
    });

    await abandonTrainingPlanVersionRpc(admin, athleteA.athleteId, plan.planVersionId, "first reason");
    const secondResult = await abandonTrainingPlanVersionRpc(admin, athleteA.athleteId, plan.planVersionId, "second call, different reason text");

    expect(secondResult.idempotentReplay).toBe(true);
    expect(secondResult.abandonedTransitionId).toBeUndefined();
  });

  it("rejects abandoning a version that is not in draft state (already accepted)", async () => {
    athleteA = await createTestAthlete(admin, "V0.4_102 abandon accepted rejected");
    const plan = await generateAndAcceptTrainingPlan(admin, athleteA.athleteId, {
      horizonStartDate: "2026-10-01",
      horizonEndDate: "2026-10-07",
      sessions: [{ date: "2026-10-01", kind: "REST" }],
    });

    await expect(abandonTrainingPlanVersionRpc(admin, athleteA.athleteId, plan.planVersionId, "should be rejected")).rejects.toThrow(
      AbandonTrainingPlanVersionRpcError
    );
  });

  it("rejects a blank reason before ever touching the lifecycle table", async () => {
    athleteA = await createTestAthlete(admin, "V0.4_102 blank reason rejected");
    const plan = await generateTrainingPlan(admin, athleteA.athleteId, {
      horizonStartDate: "2026-10-01",
      horizonEndDate: "2026-10-07",
      sessions: [{ date: "2026-10-01", kind: "REST" }],
    });

    await expect(abandonTrainingPlanVersionRpc(admin, athleteA.athleteId, plan.planVersionId, "   ")).rejects.toThrow(
      AbandonTrainingPlanVersionRpcError
    );
  });

  it("rejects abandoning a version that belongs to a different athlete", async () => {
    athleteA = await createTestAthlete(admin, "V0.4_102 cross-athlete owner");
    athleteB = await createTestAthlete(admin, "V0.4_102 cross-athlete attacker");
    const plan = await generateTrainingPlan(admin, athleteA.athleteId, {
      horizonStartDate: "2026-10-01",
      horizonEndDate: "2026-10-07",
      sessions: [{ date: "2026-10-01", kind: "REST" }],
    });

    await expect(abandonTrainingPlanVersionRpc(admin, athleteB.athleteId, plan.planVersionId, "hostile abandon")).rejects.toThrow(
      AbandonTrainingPlanVersionRpcError
    );
  });
});
