/**
 * V0.4_102 — unit coverage for abandonTrainingPlanVersionRpc.ts (mocked
 * SupabaseClient, no network). See abandonTrainingPlanVersionRpc.
 * integration.test.ts for the real-DB proof (SECURITY DEFINER grants,
 * idempotence, draft-only guard, reason enforcement).
 */
import { describe, expect, it, vi } from "vitest";
import type { SupabaseClient } from "@supabase/supabase-js";
import {
  abandonTrainingPlanVersionRpc,
  parseAbandonTrainingPlanVersionResult,
  AbandonTrainingPlanVersionRpcError,
  InvalidAbandonTrainingPlanVersionResultError,
} from "../../src/supabase/abandonTrainingPlanVersionRpc.js";

function mockClient(result: { data: unknown; error: { message: string } | null }): {
  client: SupabaseClient;
  rpc: ReturnType<typeof vi.fn>;
} {
  const rpc = vi.fn().mockResolvedValue(result);
  return { client: { rpc } as unknown as SupabaseClient, rpc };
}

describe("parseAbandonTrainingPlanVersionResult", () => {
  it("parses a fresh (non-replay) result, abandoned_transition_id present", () => {
    const result = parseAbandonTrainingPlanVersionResult({
      plan_version_id: "version-1",
      idempotent_replay: false,
      abandoned_transition_id: "transition-2",
    });

    expect(result).toEqual({ planVersionId: "version-1", idempotentReplay: false, abandonedTransitionId: "transition-2" });
  });

  it("parses an idempotent-replay result, abandonedTransitionId key entirely absent (never null)", () => {
    const result = parseAbandonTrainingPlanVersionResult({ plan_version_id: "version-1", idempotent_replay: true });

    expect(result).toEqual({ planVersionId: "version-1", idempotentReplay: true });
    expect("abandonedTransitionId" in result).toBe(false);
  });

  it("rejects a non-object payload", () => {
    expect(() => parseAbandonTrainingPlanVersionResult(null)).toThrow(InvalidAbandonTrainingPlanVersionResultError);
    expect(() => parseAbandonTrainingPlanVersionResult("version-1")).toThrow(InvalidAbandonTrainingPlanVersionResultError);
    expect(() => parseAbandonTrainingPlanVersionResult([])).toThrow(InvalidAbandonTrainingPlanVersionResultError);
  });

  it("rejects a missing or non-string plan_version_id", () => {
    expect(() => parseAbandonTrainingPlanVersionResult({ idempotent_replay: false })).toThrow(InvalidAbandonTrainingPlanVersionResultError);
    expect(() => parseAbandonTrainingPlanVersionResult({ plan_version_id: 42, idempotent_replay: false })).toThrow(
      InvalidAbandonTrainingPlanVersionResultError
    );
  });

  it("rejects a missing or non-boolean idempotent_replay", () => {
    expect(() => parseAbandonTrainingPlanVersionResult({ plan_version_id: "version-1" })).toThrow(InvalidAbandonTrainingPlanVersionResultError);
    expect(() => parseAbandonTrainingPlanVersionResult({ plan_version_id: "version-1", idempotent_replay: "false" })).toThrow(
      InvalidAbandonTrainingPlanVersionResultError
    );
  });

  it("rejects an abandoned_transition_id present but not a string", () => {
    expect(() =>
      parseAbandonTrainingPlanVersionResult({ plan_version_id: "version-1", idempotent_replay: false, abandoned_transition_id: 42 })
    ).toThrow(InvalidAbandonTrainingPlanVersionResultError);
  });
});

describe("abandonTrainingPlanVersionRpc", () => {
  it("calls the RPC with exactly the given parameters", async () => {
    const { client, rpc } = mockClient({ data: { plan_version_id: "version-1", idempotent_replay: false, abandoned_transition_id: "t-2" }, error: null });

    await abandonTrainingPlanVersionRpc(client, "athlete-1", "version-1", "regenerated by athlete");

    expect(rpc).toHaveBeenCalledWith("abandon_training_plan_version", {
      p_athlete_id: "athlete-1",
      p_plan_version_id: "version-1",
      p_reason: "regenerated by athlete",
    });
  });

  it("returns the parsed result on success", async () => {
    const { client } = mockClient({ data: { plan_version_id: "version-1", idempotent_replay: false, abandoned_transition_id: "t-2" }, error: null });

    const result = await abandonTrainingPlanVersionRpc(client, "athlete-1", "version-1", "regenerated by athlete");

    expect(result).toEqual({ planVersionId: "version-1", idempotentReplay: false, abandonedTransitionId: "t-2" });
  });

  it("throws AbandonTrainingPlanVersionRpcError on a Supabase-level error, never returns a partial result", async () => {
    const { client } = mockClient({ data: null, error: { message: "plan_version_id is not in draft state" } });

    await expect(abandonTrainingPlanVersionRpc(client, "athlete-1", "version-1", "reason")).rejects.toThrow(
      AbandonTrainingPlanVersionRpcError
    );
  });
});
