-- UX-11B.2.2 — NALYNT Execution Schema V1 (tables only).
--
-- See docs/11_DECISION_LOG.md (ADR UX-11B.1 "NALYNT Execution Model V1",
-- ADR UX-11B.2.1 "NALYNT Execution Schema V1") and docs/05_DATA_MODEL.md
-- §Modèle d'exécution V1.
--
-- Three append-only tables record what the rider actually did, against the
-- day's final prescription (decision_final_prescriptions, option A):
--   session_executions    one attempt at a session (athlete + day + displayed prescription)
--   execution_events      lifecycle: started / paused / resumed / completed / abandoned
--   exercise_set_results  one row per set; corrections via supersedes_id
--
-- Invariants enforced here (pure SQL): ownership-safe composite FKs, value
-- bounds, "prescribed item XOR other exercise", one started event per
-- execution, a set superseded at most once, no UPDATE / DELETE ever.
-- Invariants that need the day's prescription JSON or the event history
-- (item exists in the prescription, v2 only, one active execution per
-- athlete and day, lifecycle order, a correction is never corrected,
-- idempotent replays) are enforced by record_session_execution
-- (next migration), the only write path.
--
-- Additive only. The single change to an existing table is a new unique
-- constraint on decision_final_prescriptions (empty everywhere today),
-- needed for the ownership-safe composite FK below.
--
-- Load: exercise_set_results.load_kg is observed data, optional, entered by
-- the rider. The observed load belongs to the execution, never to the
-- prescription: NALYNT never prescribes a load in kg.

alter table public.decision_final_prescriptions
  add constraint decision_final_prescriptions_unique_id_athlete unique (id, athlete_id);

create type public.execution_event_type as enum ('started', 'paused', 'resumed', 'completed', 'abandoned');

create type public.set_measure_type as enum ('reps', 'duration', 'distance', 'pass');

-- ---------------------------------------------------------------------------
-- session_executions
-- ---------------------------------------------------------------------------
create table public.session_executions (
  -- Generated by the device (idempotent replays, future sync): no default.
  id uuid primary key,
  athlete_id uuid not null references public.athletes(id) on delete restrict,
  session_date date not null,
  -- Derived by the server from the final prescription, never sent by the client.
  decision_id uuid,
  final_prescription_id uuid,
  started_at timestamptz not null,
  recorded_at timestamptz not null default clock_timestamp(),
  comment text,
  constraint session_executions_unique_id_athlete unique (id, athlete_id),
  constraint session_executions_decision_fk
    foreign key (decision_id, athlete_id) references public.decisions (id, athlete_id) on delete restrict,
  constraint session_executions_final_prescription_fk
    foreign key (final_prescription_id, athlete_id)
    references public.decision_final_prescriptions (id, athlete_id) on delete restrict,
  constraint session_executions_prescription_requires_decision
    check (final_prescription_id is null or decision_id is not null),
  constraint session_executions_comment_length
    check (comment is null or (length(trim(comment)) > 0 and char_length(comment) <= 500))
);

create index idx_session_executions_athlete_date on public.session_executions (athlete_id, session_date);

-- ---------------------------------------------------------------------------
-- execution_events
-- ---------------------------------------------------------------------------
create table public.execution_events (
  id uuid primary key,
  execution_id uuid not null,
  athlete_id uuid not null,
  event_type public.execution_event_type not null,
  occurred_at timestamptz not null,
  recorded_at timestamptz not null default clock_timestamp(),
  -- Server-side insertion order: the lifecycle is evaluated in this order.
  event_seq bigint generated always as identity,
  constraint execution_events_execution_fk
    foreign key (execution_id, athlete_id) references public.session_executions (id, athlete_id) on delete restrict
);

-- One logical started event per execution (a replay of the same event id is
-- handled upstream as a no-op and never reaches this index).
create unique index idx_execution_events_one_start
  on public.execution_events (execution_id)
  where event_type = 'started';

create index idx_execution_events_execution_seq on public.execution_events (execution_id, event_seq);

-- ---------------------------------------------------------------------------
-- exercise_set_results
-- ---------------------------------------------------------------------------
create table public.exercise_set_results (
  id uuid primary key,
  execution_id uuid not null,
  athlete_id uuid not null,
  -- Stable id of an item of the day's final prescription (validated server-side).
  prescription_item_id uuid,
  -- Catalogue id, copied by the server from the prescription item, never by the client.
  exercise_id text,
  -- V1 "other exercise performed": free name, no catalogue link.
  other_exercise_name text,
  set_number integer not null,
  done boolean not null,
  measure_type public.set_measure_type not null,
  measure_value integer,
  load_kg numeric(6, 2),
  rpe_actual numeric(3, 1),
  success boolean,
  comment text,
  supersedes_id uuid references public.exercise_set_results (id) on delete restrict,
  occurred_at timestamptz not null,
  recorded_at timestamptz not null default clock_timestamp(),
  constraint exercise_set_results_execution_fk
    foreign key (execution_id, athlete_id) references public.session_executions (id, athlete_id) on delete restrict,
  constraint exercise_set_results_item_xor_other
    check ((prescription_item_id is null) <> (other_exercise_name is null)),
  constraint exercise_set_results_exercise_id_only_with_item
    check (exercise_id is null or prescription_item_id is not null),
  constraint exercise_set_results_other_name_length
    check (other_exercise_name is null or (length(trim(other_exercise_name)) > 0 and char_length(other_exercise_name) <= 80)),
  constraint exercise_set_results_set_number_positive check (set_number >= 1),
  constraint exercise_set_results_measure_value_non_negative check (measure_value is null or measure_value >= 0),
  -- A pass carries no value; any other measure needs a value unless the set was not done.
  constraint exercise_set_results_measure_value_shape check (
    (measure_type = 'pass' and measure_value is null)
    or (measure_type <> 'pass' and (measure_value is not null or not done))
  ),
  constraint exercise_set_results_load_kg_range check (load_kg is null or (load_kg >= 0 and load_kg <= 1000)),
  constraint exercise_set_results_rpe_actual_range check (rpe_actual is null or (rpe_actual >= 1 and rpe_actual <= 10)),
  constraint exercise_set_results_comment_length
    check (comment is null or (length(trim(comment)) > 0 and char_length(comment) <= 500)),
  constraint exercise_set_results_not_self_superseding check (supersedes_id is null or supersedes_id <> id)
);

-- A set is superseded at most once.
create unique index idx_exercise_set_results_supersede_once
  on public.exercise_set_results (supersedes_id)
  where supersedes_id is not null;

create index idx_exercise_set_results_execution on public.exercise_set_results (execution_id);

-- ---------------------------------------------------------------------------
-- Append-only: no UPDATE / DELETE, for anyone (same guard as the other ledgers).
-- ---------------------------------------------------------------------------
create trigger trg_session_executions_no_update
  before update on public.session_executions
  for each row execute function public.reject_append_only_mutation();
create trigger trg_session_executions_no_delete
  before delete on public.session_executions
  for each row execute function public.reject_append_only_mutation();

create trigger trg_execution_events_no_update
  before update on public.execution_events
  for each row execute function public.reject_append_only_mutation();
create trigger trg_execution_events_no_delete
  before delete on public.execution_events
  for each row execute function public.reject_append_only_mutation();

create trigger trg_exercise_set_results_no_update
  before update on public.exercise_set_results
  for each row execute function public.reject_append_only_mutation();
create trigger trg_exercise_set_results_no_delete
  before delete on public.exercise_set_results
  for each row execute function public.reject_append_only_mutation();

-- ---------------------------------------------------------------------------
-- RLS: the rider reads only their own rows. No direct write path for anyone
-- but the table owner: record_session_execution (SECURITY DEFINER) is the
-- only writer, callable by service_role only.
-- ---------------------------------------------------------------------------
alter table public.session_executions enable row level security;
alter table public.execution_events enable row level security;
alter table public.exercise_set_results enable row level security;

create policy "session_executions_own_select"
  on public.session_executions
  for select
  to authenticated
  using (athlete_id in (select athletes.id from public.athletes where athletes.user_id = auth.uid()));

create policy "execution_events_own_select"
  on public.execution_events
  for select
  to authenticated
  using (athlete_id in (select athletes.id from public.athletes where athletes.user_id = auth.uid()));

create policy "exercise_set_results_own_select"
  on public.exercise_set_results
  for select
  to authenticated
  using (athlete_id in (select athletes.id from public.athletes where athletes.user_id = auth.uid()));

revoke all privileges on public.session_executions from anon, authenticated, service_role;
revoke all privileges on public.execution_events from anon, authenticated, service_role;
revoke all privileges on public.exercise_set_results from anon, authenticated, service_role;

grant select on public.session_executions to authenticated, service_role;
grant select on public.execution_events to authenticated, service_role;
grant select on public.exercise_set_results to authenticated, service_role;
