-- completed_sessions upsert-only security regression check — strictly
-- read-only.
--
-- Purpose: catch a future regression where `authenticated` (or `anon`)
-- regains direct INSERT/UPDATE/DELETE on public.completed_sessions, where
-- the expected SELECT-only policy disappears, or where
-- persist_completed_session's security posture drifts (wrong SECURITY
-- mode, wrong EXECUTE grants, service_role losing what the RPC needs) —
-- silently reopening the exact hole fixed by
-- 20260819211500_completed_sessions_upsert_only_security.sql (empirically
-- reproduced locally: authenticated could INSERT/UPDATE/DELETE its own
-- completed_sessions rows directly, bypassing persist_completed_session,
-- before that migration).
--
-- Every section below is written so that an EMPTY result means "healthy".
-- A non-empty row from any section is a real regression: run this
-- preflight, read which row came back, and treat it exactly like a failing
-- test — do not edit this file to make it pass.
--
-- Sections H onward target the RPC by its EXACT signature
-- (to_regprocedure('public.persist_completed_session(uuid,jsonb)')) rather
-- than matching on proname alone — a future overload with a different
-- argument list must never make this preflight ambiguous about which
-- function it is actually checking.
--
-- This file contains ONLY SELECT statements. No INSERT / UPDATE / DELETE /
-- CREATE / ALTER / DROP / TRUNCATE / GRANT / REVOKE / CALL. Safe to run
-- against local or the linked remote project at any time (e.g. via a
-- read-only MCP connection or role), and versioned for audit.

-- ===========================================================================
-- A. RLS must be enabled on completed_sessions.
-- ===========================================================================
select
  relname,
  relrowsecurity,
  'RLS must be enabled on completed_sessions' as problem
from pg_class
where oid = 'public.completed_sessions'::regclass
  and relrowsecurity = false;

-- ===========================================================================
-- B. The expected policy must exist, named exactly
--    completed_sessions_own_select, FOR SELECT, targeting exactly the
--    authenticated role (via polroles — not PUBLIC, not a different or
--    additional role). Catalog-level check, not string-matching the USING
--    expression itself: the empirical cross-athlete SELECT proof remains
--    the authoritative test of ownership semantics, not this preflight.
-- ===========================================================================
select 'completed_sessions_own_select policy (FOR SELECT, role=authenticated) is missing or misconfigured' as problem
where not exists (
  select 1 from pg_policy pol
  where pol.polrelid = 'public.completed_sessions'::regclass
    and pol.polname = 'completed_sessions_own_select'
    and pol.polcmd = 'r'
    and pol.polroles = array[('authenticated'::regrole)::oid]
);

-- ===========================================================================
-- C. No policy other than completed_sessions_own_select may exist at all
--    — catches wrong-command policies AND unexpected additional policies
--    (including a second, differently-named SELECT policy that section B
--    alone would not detect, since B only checks that the expected one
--    exists, not that it's the only one).
-- ===========================================================================
select
  pol.polname,
  pol.polcmd,
  'unexpected policy on completed_sessions (only completed_sessions_own_select should exist)' as problem
from pg_policy pol
where pol.polrelid = 'public.completed_sessions'::regclass
  and pol.polname <> 'completed_sessions_own_select';

-- ===========================================================================
-- C2. Exactly one policy total must exist on completed_sessions (belt and
--     suspenders alongside B/C: a duplicate correctly-named policy would
--     satisfy both B and C individually but still be a misconfiguration).
-- ===========================================================================
select count(*) as policy_count, 'completed_sessions must have exactly 1 policy' as problem
from pg_policy
where polrelid = 'public.completed_sessions'::regclass
having count(*) <> 1;

-- ===========================================================================
-- D. authenticated must have SELECT on completed_sessions...
-- ===========================================================================
select 'authenticated is missing SELECT on completed_sessions' as problem
where not exists (
  select 1 from information_schema.role_table_grants
  where table_schema = 'public' and table_name = 'completed_sessions'
    and grantee = 'authenticated' and privilege_type = 'SELECT'
);

-- ===========================================================================
-- E. ...and no direct write privilege on completed_sessions.
-- ===========================================================================
select
  grantee,
  privilege_type,
  'unexpected write privilege on completed_sessions' as problem
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'completed_sessions'
  and grantee = 'authenticated'
  and privilege_type <> 'SELECT';

-- ===========================================================================
-- F. anon must hold no privilege at all on completed_sessions.
-- ===========================================================================
select
  grantee,
  privilege_type,
  'anon must have zero privileges on completed_sessions' as problem
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'completed_sessions'
  and grantee = 'anon';

-- ===========================================================================
-- G. service_role must retain exactly what persist_completed_session
--    needs: SELECT on decisions (to validate decision_id linkage), and
--    SELECT/INSERT/UPDATE on completed_sessions (to upsert).
-- ===========================================================================
select 'service_role is missing SELECT on decisions' as problem
where not exists (
  select 1 from information_schema.role_table_grants
  where table_schema = 'public' and table_name = 'decisions'
    and grantee = 'service_role' and privilege_type = 'SELECT'
);

select
  needed.priv,
  'service_role is missing ' || needed.priv || ' on completed_sessions' as problem
from unnest(array['SELECT', 'INSERT', 'UPDATE']) as needed(priv)
where not exists (
  select 1 from information_schema.role_table_grants
  where table_schema = 'public' and table_name = 'completed_sessions'
    and grantee = 'service_role' and privilege_type = needed.priv
);

-- ===========================================================================
-- H. persist_completed_session(uuid, jsonb) must exist with this exact
--    signature. If this returns a row, every check below it is
--    inconclusive by construction (there is no function to check) — fix
--    this one first.
-- ===========================================================================
select 'public.persist_completed_session(uuid, jsonb) does not exist with this exact signature' as problem
where to_regprocedure('public.persist_completed_session(uuid, jsonb)') is null;

-- ===========================================================================
-- I. persist_completed_session(uuid, jsonb) must be SECURITY INVOKER.
-- ===========================================================================
select
  p.prosecdef as security_definer,
  'persist_completed_session(uuid, jsonb) must be SECURITY INVOKER' as problem
from pg_proc p
where p.oid = to_regprocedure('public.persist_completed_session(uuid, jsonb)')
  and p.prosecdef = true;

-- ===========================================================================
-- J. anon must not be able to EXECUTE persist_completed_session(uuid, jsonb).
-- ===========================================================================
select 'anon must not be able to execute persist_completed_session(uuid, jsonb)' as problem
where has_function_privilege(
  'anon', to_regprocedure('public.persist_completed_session(uuid, jsonb)'), 'EXECUTE'
);

-- ===========================================================================
-- K. authenticated must not be able to EXECUTE
--    persist_completed_session(uuid, jsonb) — all writes must go through
--    the future M5_003 Edge Function's service_role client, never
--    directly from the browser.
-- ===========================================================================
select 'authenticated must not be able to execute persist_completed_session(uuid, jsonb)' as problem
where has_function_privilege(
  'authenticated', to_regprocedure('public.persist_completed_session(uuid, jsonb)'), 'EXECUTE'
);

-- ===========================================================================
-- L. service_role must be able to EXECUTE
--    persist_completed_session(uuid, jsonb) — the one legitimate write
--    path this whole fix exists to protect.
-- ===========================================================================
select 'service_role must be able to execute persist_completed_session(uuid, jsonb)' as problem
where not has_function_privilege(
  'service_role', to_regprocedure('public.persist_completed_session(uuid, jsonb)'), 'EXECUTE'
);

-- ===========================================================================
-- M. Informational — expected healthy state, for a human to eyeball
--    alongside A-L returning empty.
-- ===========================================================================
select
  grantee,
  privilege_type
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'completed_sessions'
  and grantee in ('authenticated', 'service_role')
order by grantee, privilege_type;

select
  p.proname,
  pg_get_function_identity_arguments(p.oid) as args,
  p.prosecdef as security_definer,
  has_function_privilege('anon', p.oid, 'EXECUTE') as anon_can_execute,
  has_function_privilege('authenticated', p.oid, 'EXECUTE') as authenticated_can_execute,
  has_function_privilege('service_role', p.oid, 'EXECUTE') as service_role_can_execute
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public'
  and p.proname = 'persist_completed_session';
-- Healthy row: security_definer=f, anon_can_execute=f,
-- authenticated_can_execute=f, service_role_can_execute=t.
