-- decision_outcomes append-only security regression check — strictly
-- read-only.
--
-- Purpose: catch a future regression where `authenticated` (or `anon`)
-- gains any direct write privilege on public.decision_outcomes, where the
-- expected SELECT-only policy disappears, or where
-- persist_decision_outcome's security posture drifts (wrong SECURITY
-- mode, wrong EXECUTE grants, service_role gaining UPDATE/DELETE it
-- should never need) — this table has no legitimate mutation path at all
-- once a row exists, and this preflight exists to keep it that way.
--
-- Every section below is written so that an EMPTY result means "healthy".
-- A non-empty row from any section is a real regression: run this
-- preflight, read which row came back, and treat it exactly like a failing
-- test — do not edit this file to make it pass.
--
-- Sections H onward target the RPC by its EXACT signature
-- (to_regprocedure('public.persist_decision_outcome(uuid, jsonb)')) rather
-- than matching on proname alone — a future overload must never make this
-- preflight ambiguous about which function it is actually checking.
--
-- This file contains ONLY SELECT statements. No INSERT / UPDATE / DELETE /
-- CREATE / ALTER / DROP / TRUNCATE / GRANT / REVOKE / CALL. Safe to run
-- against local or the linked remote project at any time, and versioned
-- for audit.

-- ===========================================================================
-- A. RLS must be enabled on decision_outcomes.
-- ===========================================================================
select
  relname,
  relrowsecurity,
  'RLS must be enabled on decision_outcomes' as problem
from pg_class
where oid = 'public.decision_outcomes'::regclass
  and relrowsecurity = false;

-- ===========================================================================
-- B. The expected policy must exist, named exactly
--    decision_outcomes_own_select, FOR SELECT, targeting exactly the
--    authenticated role (via polroles — not PUBLIC, not a different or
--    additional role).
-- ===========================================================================
select 'decision_outcomes_own_select policy (FOR SELECT, role=authenticated) is missing or misconfigured' as problem
where not exists (
  select 1 from pg_policy pol
  where pol.polrelid = 'public.decision_outcomes'::regclass
    and pol.polname = 'decision_outcomes_own_select'
    and pol.polcmd = 'r'
    and pol.polroles = array[('authenticated'::regrole)::oid]
);

-- ===========================================================================
-- C. No policy other than decision_outcomes_own_select may exist at all.
-- ===========================================================================
select
  pol.polname,
  pol.polcmd,
  'unexpected policy on decision_outcomes (only decision_outcomes_own_select should exist)' as problem
from pg_policy pol
where pol.polrelid = 'public.decision_outcomes'::regclass
  and pol.polname <> 'decision_outcomes_own_select';

-- ===========================================================================
-- C2. Exactly one policy total must exist on decision_outcomes.
-- ===========================================================================
select count(*) as policy_count, 'decision_outcomes must have exactly 1 policy' as problem
from pg_policy
where polrelid = 'public.decision_outcomes'::regclass
having count(*) <> 1;

-- ===========================================================================
-- D. authenticated must have SELECT on decision_outcomes...
-- ===========================================================================
select 'authenticated is missing SELECT on decision_outcomes' as problem
where not exists (
  select 1 from information_schema.role_table_grants
  where table_schema = 'public' and table_name = 'decision_outcomes'
    and grantee = 'authenticated' and privilege_type = 'SELECT'
);

-- ===========================================================================
-- E. ...and no direct write privilege on decision_outcomes at all —
--    INSERT/UPDATE/DELETE must never reach authenticated, unlike
--    completed_sessions where SELECT was the only allowed non-write
--    privilege; here there is additionally no legitimate INSERT path for
--    authenticated either (only service_role, via the RPC, ever inserts).
-- ===========================================================================
select
  grantee,
  privilege_type,
  'unexpected write privilege on decision_outcomes' as problem
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'decision_outcomes'
  and grantee = 'authenticated'
  and privilege_type <> 'SELECT';

-- ===========================================================================
-- F. anon must hold zero privileges at all on decision_outcomes.
-- ===========================================================================
select
  grantee,
  privilege_type,
  'anon must have zero privileges on decision_outcomes' as problem
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'decision_outcomes'
  and grantee = 'anon';

-- ===========================================================================
-- G. service_role must have exactly SELECT and INSERT on
--    decision_outcomes — never UPDATE/DELETE (this table has no
--    legitimate mutation path once a row exists; persist_decision_outcome
--    only ever INSERTs).
-- ===========================================================================
select
  needed.priv,
  'service_role is missing ' || needed.priv || ' on decision_outcomes' as problem
from unnest(array['SELECT', 'INSERT']) as needed(priv)
where not exists (
  select 1 from information_schema.role_table_grants
  where table_schema = 'public' and table_name = 'decision_outcomes'
    and grantee = 'service_role' and privilege_type = needed.priv
);

select
  grantee,
  privilege_type,
  'service_role must not have UPDATE/DELETE on decision_outcomes' as problem
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'decision_outcomes'
  and grantee = 'service_role'
  and privilege_type in ('UPDATE', 'DELETE');

-- ===========================================================================
-- H. persist_decision_outcome(uuid, jsonb) must exist with this exact
--    signature. If this returns a row, every check below it is
--    inconclusive by construction — fix this one first.
-- ===========================================================================
select 'public.persist_decision_outcome(uuid, jsonb) does not exist with this exact signature' as problem
where to_regprocedure('public.persist_decision_outcome(uuid, jsonb)') is null;

-- ===========================================================================
-- I. persist_decision_outcome(uuid, jsonb) must be SECURITY INVOKER.
-- ===========================================================================
select
  p.prosecdef as security_definer,
  'persist_decision_outcome(uuid, jsonb) must be SECURITY INVOKER' as problem
from pg_proc p
where p.oid = to_regprocedure('public.persist_decision_outcome(uuid, jsonb)')
  and p.prosecdef = true;

-- ===========================================================================
-- J. anon must not be able to EXECUTE persist_decision_outcome(uuid, jsonb).
-- ===========================================================================
select 'anon must not be able to execute persist_decision_outcome(uuid, jsonb)' as problem
where has_function_privilege(
  'anon', to_regprocedure('public.persist_decision_outcome(uuid, jsonb)'), 'EXECUTE'
);

-- ===========================================================================
-- K. authenticated must not be able to EXECUTE
--    persist_decision_outcome(uuid, jsonb).
-- ===========================================================================
select 'authenticated must not be able to execute persist_decision_outcome(uuid, jsonb)' as problem
where has_function_privilege(
  'authenticated', to_regprocedure('public.persist_decision_outcome(uuid, jsonb)'), 'EXECUTE'
);

-- ===========================================================================
-- L. service_role must be able to EXECUTE
--    persist_decision_outcome(uuid, jsonb) — the one legitimate write path
--    this whole fix exists to protect.
-- ===========================================================================
select 'service_role must be able to execute persist_decision_outcome(uuid, jsonb)' as problem
where not has_function_privilege(
  'service_role', to_regprocedure('public.persist_decision_outcome(uuid, jsonb)'), 'EXECUTE'
);

-- ===========================================================================
-- M. Informational — expected healthy state, for a human to eyeball
--    alongside A-L returning empty.
-- ===========================================================================
select
  grantee,
  privilege_type
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'decision_outcomes'
  and grantee in ('authenticated', 'service_role', 'anon')
order by grantee, privilege_type;

select
  p.proname,
  pg_get_function_identity_arguments(p.oid) as args,
  p.prosecdef as security_definer,
  has_function_privilege('anon', p.oid, 'EXECUTE') as anon_can_execute,
  has_function_privilege('authenticated', p.oid, 'EXECUTE') as authenticated_can_execute,
  has_function_privilege('service_role', p.oid, 'EXECUTE') as service_role_can_execute
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public'
  and p.proname = 'persist_decision_outcome';
-- Healthy row: security_definer=f, anon_can_execute=f,
-- authenticated_can_execute=f, service_role_can_execute=t.
