-- decisions append-only security regression check — strictly read-only.
--
-- Purpose: catch a future regression where `authenticated` (or `anon`)
-- regains direct INSERT/UPDATE/DELETE on public.decisions, silently
-- reopening the hole fixed by 20260819200000_decisions_append_only_security.sql
-- (empirically proven locally: authenticated could INSERT/UPDATE/DELETE its
-- own decisions rows directly, bypassing public.persist_daily_run, before
-- that migration).
--
-- Every section below is written so that an EMPTY result means "healthy".
-- A non-empty row from any of sections A-C is a real regression: run this
-- preflight, read which row came back, and treat it exactly like a failing
-- test — do not edit this file to make it pass.
--
-- This file contains ONLY SELECT statements. No INSERT / UPDATE / DELETE /
-- CREATE / ALTER / DROP / TRUNCATE / GRANT / REVOKE / CALL. Safe to run
-- against local or the linked remote project at any time (e.g. via a
-- read-only MCP connection or role), and versioned for audit.

-- ===========================================================================
-- A. No policy other than a SELECT-only one may target authenticated on
--    decisions. polcmd values: r=SELECT, a=INSERT, w=UPDATE, d=DELETE,
--    *=ALL. Anything here other than 'r' is the exact regression this
--    check exists to catch.
-- ===========================================================================
select
  pol.polname,
  pol.polcmd,
  'unexpected non-SELECT-only policy on decisions' as problem
from pg_policy pol
where pol.polrelid = 'public.decisions'::regclass
  and pol.polcmd <> 'r';

-- ===========================================================================
-- B. authenticated/anon must hold no write privilege on decisions.
-- ===========================================================================
select
  grantee,
  privilege_type,
  'unexpected write privilege on decisions' as problem
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'decisions'
  and grantee in ('authenticated', 'anon')
  and privilege_type <> 'SELECT';

-- ===========================================================================
-- C. anon must hold no privilege at all on decisions (not even SELECT —
--    there is no anon-targeted policy, so a SELECT grant would be dead
--    but present privilege, against least-privilege intent).
-- ===========================================================================
select
  grantee,
  privilege_type,
  'anon must have zero privileges on decisions' as problem
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'decisions'
  and grantee = 'anon';

-- ===========================================================================
-- D. Informational — expected healthy state, for a human to eyeball
--    alongside A-C returning empty. authenticated should show exactly one
--    row (SELECT), service_role should show its full write set.
-- ===========================================================================
select
  grantee,
  privilege_type
from information_schema.role_table_grants
where table_schema = 'public'
  and table_name = 'decisions'
  and grantee in ('authenticated', 'service_role')
order by grantee, privilege_type;

-- ===========================================================================
-- E. persist_daily_run must remain SECURITY INVOKER, EXECUTE denied for
--    anon/authenticated, allowed for service_role — the one legitimate
--    write path this whole fix exists to protect.
-- ===========================================================================
select
  p.proname,
  p.prosecdef as security_definer,
  has_function_privilege('anon', p.oid, 'EXECUTE') as anon_can_execute,
  has_function_privilege('authenticated', p.oid, 'EXECUTE') as authenticated_can_execute,
  has_function_privilege('service_role', p.oid, 'EXECUTE') as service_role_can_execute
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public'
  and p.proname = 'persist_daily_run';
-- Healthy row: security_definer=f, anon_can_execute=f,
-- authenticated_can_execute=f, service_role_can_execute=t.
